<?php

return [
    [
        'name' => 'number',
        'title' => '数字',
        'default_define' => "int(10) UNSIGNED NOT NULL DEFAULT '0'",
        'ifoption' => 0,
        'ifstring' => 0,
    ],
    [
        'name' => 'text',
        'title' => '输入框',
        'default_define' => "varchar(255) NOT NULL DEFAULT ''",
        'ifoption' => 0,
        'ifstring' => 1,
    ],
    [
        'name' => 'textarea',
        'title' => '多行文本',
        'default_define' => "varchar(255) NOT NULL DEFAULT ''",
        'ifoption' => 0,
        'ifstring' => 1,
    ],
    [
        'name' => 'radio',
        'title' => '单选按钮',
        'default_define' => "varchar(10) NOT NULL DEFAULT ''",
        'ifoption' => 1,
        'ifstring' => 0,
    ],
    [
        'name' => 'checkbox',
        'title' => '复选按钮',
        'default_define' => "varchar(32) NOT NULL DEFAULT ''",
        'ifoption' => 1,
        'ifstring' => 0,
    ],
    [
        'name' => 'switch',
        'title' => '开关',
        'default_define' => "tinyint(2) UNSIGNED NOT NULL DEFAULT '0'",
        'ifoption' => 0,
        'ifstring' => 0,
    ],
    [
        'name' => 'select',
        'title' => '下拉框',
        'default_define' => "varchar(10) NOT NULL DEFAULT ''",
        'ifoption' => 1,
        'ifstring' => 0,
    ],
    [
        'name' => 'array',
        'title' => '数组',
        'default_define' => "varchar(512) NOT NULL DEFAULT ''",
        'ifoption' => 0,
        'ifstring' => 0,
    ],
    [
        'name' => 'image',
        'title' => '单张图',
        'default_define' => "varchar(32) NOT NULL DEFAULT ''",
        'ifoption' => 0,
        'ifstring' => 0,
    ],
    [
        'name' => 'images',
        'title' => '多张图',
        'default_define' => "text NOT NULL DEFAULT ''",
        'ifoption' => 0,
        'ifstring' => 0,
    ],
    [
        'name' => 'color',
        'title' => '颜色值',
        'default_define' => "varchar(7) NOT NULL DEFAULT ''",
        'ifoption' => 0,
        'ifstring' => 0,
    ],
    [
        'name' => 'date',
        'title' => '日期',
        'default_define' => "int(10) UNSIGNED NOT NULL DEFAULT '0'",
        'ifoption' => 0,
        'ifstring' => 0,
    ],
    [
        'name' => 'datetime',
        'title' => '日期和时间',
        'default_define' => "int(10) UNSIGNED NOT NULL DEFAULT '0'",
        'ifoption' => 0,
        'ifstring' => 0,
    ],
    [
        'name' => 'file',
        'title' => '单文件',
        'default_define' => "varchar(32) NOT NULL DEFAULT ''",
        'ifoption' => 0,
        'ifstring' => 0,
    ],
    [
        'name' => 'files',
        'title' => '多文件',
        'default_define' => "text NOT NULL DEFAULT ''",
        'ifoption' => 0,
        'ifstring' => 0,
    ],
    [
        'name' => 'hidden',
        'title' => '隐藏值',
        'default_define' => "varchar(255) NOT NULL DEFAULT ''",
        'ifoption' => 0,
        'ifstring' => 1,
    ],
    [
        'name' => 'password',
        'title' => '密码',
        'default_define' => "varchar(255) NOT NULL DEFAULT ''",
        'ifoption' => 0,
        'ifstring' => 1,
    ],
    [
        'name' => 'tags',
        'title' => '标签',
        'default_define' => "varchar(255) NOT NULL DEFAULT ''",
        'ifoption' => 0,
        'ifstring' => 1,
    ],
    [
        'name' => 'editor',
        'title' => '编辑器',
        'default_define' => "text NOT NULL DEFAULT ''",
        'ifoption' => 0,
        'ifstring' => 1,
    ],

];
