<?php
return [
    "title" => "内容管理",
    "url" => "cms/index",
    "method" => "GET",
    "slug" => $slug,
    "icon" => "icon-shiyongwendang",
    "menu_show" => 1,
    "listorder" => 1035,
    "remark" => "",
    "children" => [
        [
            "title" => "管理内容",
            "url" => "cms/content/index",
            "method" => "OPTIONS",
            "slug" => "admin.cms.content-index",
            "icon" => "icon-neirongguanli",
            "listorder" => 10,
            "menu_show" => 1,
            "children" => [
                [
                    "url" => "cms/content/index",
                    "method" => "GET",
                    "slug" => "admin.cms.content-index",
                    "listorder" => 1,
                    "menu_show" => 0,
                    "title" => "管理内容",
                ],
                [
                    "url" => "cms/content/main",
                    "method" => "GET",
                    "slug" => "admin.cms.content-main",
                    "listorder" => 2,
                    "menu_show" => 0,
                    "title" => "内容首页",
                ],
                [
                    "url" => "cms/content/page",
                    "method" => "GET",
                    "slug" => "admin.cms.content-page",
                    "listorder" => 3,
                    "menu_show" => 0,
                    "title" => "内容单页",
                ],
                [
                    "url" => "cms/content/page",
                    "method" => "POST",
                    "slug" => "admin.cms.content-page-save",
                    "listorder" => 4,
                    "menu_show" => 0,
                    "title" => "内容单页保存",
                ],
                [
                    "url" => "cms/content/cate",
                    "method" => "GET",
                    "slug" => "admin.cms.content-cate",
                    "listorder" => 5,
                    "menu_show" => 0,
                    "title" => "内容列表",
                ],
                [
                    "url" => "cms/content/cate",
                    "method" => "POST",
                    "slug" => "admin.cms.content-cate-save",
                    "listorder" => 6,
                    "menu_show" => 0,
                    "title" => "内容列表保存",
                ],
                [
                    "url" => "cms/content/add",
                    "method" => "GET",
                    "slug" => "admin.cms.content-add",
                    "listorder" => 7,
                    "menu_show" => 0,
                    "title" => "添加",
                ],
                [
                    "url" => "cms/content/add",
                    "method" => "POST",
                    "slug" => "admin.cms.content-add-save",
                    "listorder" => 8,
                    "menu_show" => 0,
                    "title" => "添加保存",
                ],
                [
                    "url" => "cms/content/edit",
                    "method" => "GET",
                    "slug" => "admin.cms.content-edit",
                    "listorder" => 9,
                    "menu_show" => 0,
                    "title" => "编辑",
                ],
                [
                    "url" => "cms/content/edit",
                    "method" => "POST",
                    "slug" => "admin.cms.content-edit-save",
                    "listorder" => 10,
                    "menu_show" => 0,
                    "title" => "编辑保存",
                ],
                [
                    "url" => "cms/content/delete",
                    "method" => "POST",
                    "slug" => "admin.cms.content-delete",
                    "listorder" => 11,
                    "menu_show" => 0,
                    "title" => "删除",
                ],
                [
                    "url" => "cms/content/state",
                    "method" => "POST",
                    "slug" => "admin.cms.content-state",
                    "listorder" => 12,
                    "menu_show" => 0,
                    "title" => "设置状态",
                ],
            ],
        ],
        
        [
            "url" => "cms/navbar/index",
            "method" => "OPTIONS",
            "slug" => "admin.cms.navbar-index",
            "menu_show" => 1,
            "title" => "CMS设置",
            "icon" => "icon-shiyongwendang",
            "listorder" => 20,
            "children" => [
                [
                    "url" => "cms/navbar/index",
                    "method" => "OPTIONS",
                    "slug" => "admin.cms.navbar-index",
                    "menu_show" => 1,
                    "title" => "导航管理",
                    "icon" => "icon-liebiaosousuo",
                    "listorder" => 10,
                    "children" => [
                        [
                            "url" => "cms/navbar/index",
                            "method" => "GET",
                            "slug" => "admin.cms.navbar-index",
                            "listorder" => 1,
                            "menu_show" => 0,
                            "title" => "导航管理",
                        ],
                        [
                            "url" => "cms/navbar/index",
                            "method" => "POST",
                            "slug" => "admin.cms.navbar-index-data",
                            "listorder" => 2,
                            "menu_show" => 0,
                            "title" => "导航管理数据",
                        ],
                        [
                            "url" => "cms/navbar/all",
                            "method" => "GET",
                            "slug" => "admin.cms.navbar-all",
                            "listorder" => 3,
                            "menu_show" => 0,
                            "title" => "全部导航",
                        ],
                        [
                            "url" => "cms/navbar/all",
                            "method" => "POST",
                            "slug" => "admin.cms.navbar-all-data",
                            "listorder" => 4,
                            "menu_show" => 0,
                            "title" => "全部导航数据",
                        ],
                        [
                            "url" => "cms/navbar/add",
                            "method" => "GET",
                            "slug" => "admin.cms.navbar-add",
                            "listorder" => 5,
                            "menu_show" => 0,
                            "title" => "添加导航",
                        ],
                        [
                            "url" => "cms/navbar/add",
                            "method" => "POST",
                            "slug" => "admin.cms.navbar-add-save",
                            "listorder" => 6,
                            "menu_show" => 0,
                            "title" => "添加导航保存",
                        ],
                        [
                            "url" => "cms/navbar/edit",
                            "method" => "GET",
                            "slug" => "admin.cms.navbar-edit",
                            "listorder" => 7,
                            "menu_show" => 0,
                            "title" => "编辑导航",
                        ],
                        [
                            "url" => "cms/navbar/edit",
                            "method" => "POST",
                            "slug" => "admin.cms.navbar-edit-save",
                            "listorder" => 8,
                            "menu_show" => 0,
                            "title" => "编辑导航保存",
                        ],
                        [
                            "url" => "cms/navbar/delete",
                            "method" => "POST",
                            "slug" => "admin.cms.navbar-delete",
                            "listorder" => 9,
                            "menu_show" => 0,
                            "title" => "删除导航",
                        ],
                        [
                            "url" => "cms/navbar/sort",
                            "method" => "POST",
                            "slug" => "admin.cms.navbar-sort",
                            "listorder" => 10,
                            "menu_show" => 0,
                            "title" => "导航排序",
                        ],
                        [
                            "url" => "cms/navbar/state",
                            "method" => "POST",
                            "slug" => "admin.cms.navbar-state",
                            "listorder" => 11,
                            "menu_show" => 0,
                            "title" => "导航状态",
                        ],
                    ],
                ],
                
                [
                    "url" => "cms/tags/index",
                    "method" => "OPTIONS",
                    "slug" => "admin.cms.tags-index",
                    "menu_show" => 1,
                    "title" => "标签管理",
                    "icon" => "icon-label",
                    "listorder" => 30,
                    "children" => [
                        [
                            "url" => "cms/tags/index",
                            "method" => "GET",
                            "slug" => "admin.cms.tags-index",
                            "listorder" => 1,
                            "menu_show" => 0,
                            "title" => "标签管理",
                        ],
                        [
                            "url" => "cms/tags/index",
                            "method" => "POST",
                            "slug" => "admin.cms.tags-index-data",
                            "listorder" => 2,
                            "menu_show" => 0,
                            "title" => "标签管理数据",
                        ],
                        [
                            "url" => "cms/tags/add",
                            "method" => "GET",
                            "slug" => "admin.cms.tags-add",
                            "listorder" => 3,
                            "menu_show" => 0,
                            "title" => "添加标签",
                        ],
                        [
                            "url" => "cms/tags/add",
                            "method" => "POST",
                            "slug" => "admin.cms.tags-add-save",
                            "listorder" => 4,
                            "menu_show" => 0,
                            "title" => "添加标签保存",
                        ],
                        [
                            "url" => "cms/tags/edit",
                            "method" => "GET",
                            "slug" => "admin.cms.tags-edit",
                            "listorder" => 5,
                            "menu_show" => 0,
                            "title" => "编辑标签",
                        ],
                        [
                            "url" => "cms/tags/edit",
                            "method" => "POST",
                            "slug" => "admin.cms.tags-edit-save",
                            "listorder" => 6,
                            "menu_show" => 0,
                            "title" => "编辑标签保存",
                        ],
                        [
                            "url" => "cms/tags/delete",
                            "method" => "POST",
                            "slug" => "admin.cms.tags-delete",
                            "listorder" => 7,
                            "menu_show" => 0,
                            "title" => "删除标签",
                        ],
                        [
                            "url" => "cms/tags/sort",
                            "method" => "POST",
                            "slug" => "admin.cms.tags-sort",
                            "listorder" => 8,
                            "menu_show" => 0,
                            "title" => "标签排序",
                        ],
                        [
                            "url" => "cms/tags/state",
                            "method" => "POST",
                            "slug" => "admin.cms.tags-state",
                            "listorder" => 9,
                            "menu_show" => 0,
                            "title" => "标签状态",
                        ],
                    ],
                ],
                
                [
                    "url" => "cms/category/index",
                    "method" => "OPTIONS",
                    "slug" => "admin.cms.category-index",
                    "menu_show" => 1,
                    "title" => "栏目管理",
                    "icon" => "icon-other",
                    "listorder" => 50,
                    "children" => [
                        [
                            "url" => "cms/category/index",
                            "method" => "GET",
                            "slug" => "admin.cms.category-index",
                            "listorder" => 1,
                            "menu_show" => 0,
                            "title" => "栏目管理",
                        ],
                        [
                            "url" => "cms/category/index",
                            "method" => "POST",
                            "slug" => "admin.cms.category-index-data",
                            "listorder" => 2,
                            "menu_show" => 0,
                            "title" => "栏目管理数据",
                        ],
                        [
                            "url" => "cms/category/all",
                            "method" => "GET",
                            "slug" => "admin.cms.category-all",
                            "listorder" => 3,
                            "menu_show" => 0,
                            "title" => "全部栏目",
                        ],
                        [
                            "url" => "cms/category/all",
                            "method" => "POST",
                            "slug" => "admin.cms.category-all-data",
                            "listorder" => 4,
                            "menu_show" => 0,
                            "title" => "全部栏目数据",
                        ],
                        [
                            "url" => "cms/category/add",
                            "method" => "GET",
                            "slug" => "admin.cms.category-add",
                            "listorder" => 5,
                            "menu_show" => 0,
                            "title" => "添加栏目",
                        ],
                        [
                            "url" => "cms/category/add",
                            "method" => "POST",
                            "slug" => "admin.cms.category-add-save",
                            "listorder" => 6,
                            "menu_show" => 0,
                            "title" => "添加栏目保存",
                        ],
                        [
                            "url" => "cms/category/edit",
                            "method" => "GET",
                            "slug" => "admin.cms.category-edit",
                            "listorder" => 7,
                            "menu_show" => 0,
                            "title" => "编辑栏目",
                        ],
                        [
                            "url" => "cms/category/edit",
                            "method" => "POST",
                            "slug" => "admin.cms.category-edit-save",
                            "listorder" => 8,
                            "menu_show" => 0,
                            "title" => "编辑栏目保存",
                        ],
                        [
                            "url" => "cms/category/setting",
                            "method" => "GET",
                            "slug" => "admin.cms.category-setting",
                            "listorder" => 9,
                            "menu_show" => 0,
                            "title" => "栏目设置",
                        ],
                        [
                            "url" => "cms/category/setting",
                            "method" => "POST",
                            "slug" => "admin.cms.category-setting-save",
                            "listorder" => 10,
                            "menu_show" => 0,
                            "title" => "栏目设置保存",
                        ],
                        [
                            "url" => "cms/category/delete",
                            "method" => "POST",
                            "slug" => "admin.cms.category-delete",
                            "listorder" => 11,
                            "menu_show" => 0,
                            "title" => "删除栏目",
                        ],
                        [
                            "url" => "cms/category/sort",
                            "method" => "POST",
                            "slug" => "admin.cms.category-sort",
                            "listorder" => 12,
                            "menu_show" => 0,
                            "title" => "栏目排序",
                        ],
                        [
                            "url" => "cms/category/state",
                            "method" => "POST",
                            "slug" => "admin.cms.category-state",
                            "listorder" => 13,
                            "menu_show" => 0,
                            "title" => "栏目状态",
                        ],
                    ],
                ],
                
                [
                    "url" => "cms/field/index",
                    "method" => "OPTIONS",
                    "slug" => "admin.cms.field-index",
                    "menu_show" => 0,
                    "title" => "字段管理",
                    "icon" => "icon-apartment",
                    "listorder" => 60,
                    "children" => [
                        [
                            "url" => "cms/field/index",
                            "method" => "GET",
                            "slug" => "admin.cms.field-index",
                            "listorder" => 1,
                            "menu_show" => 0,
                            "title" => "字段管理",
                        ],
                        [
                            "url" => "cms/field/index",
                            "method" => "POST",
                            "slug" => "admin.cms.field-index-data",
                            "listorder" => 2,
                            "menu_show" => 0,
                            "title" => "字段管理数据",
                        ],
                        [
                            "url" => "cms/field/add",
                            "method" => "GET",
                            "slug" => "admin.cms.field-add",
                            "listorder" => 3,
                            "menu_show" => 0,
                            "title" => "字段添加",
                        ],
                        [
                            "url" => "cms/field/add",
                            "method" => "POST",
                            "slug" => "admin.cms.field-add-save",
                            "listorder" => 4,
                            "menu_show" => 0,
                            "title" => "字段添加保存",
                        ],
                        [
                            "url" => "cms/field/edit",
                            "method" => "GET",
                            "slug" => "admin.cms.field-edit",
                            "listorder" => 5,
                            "menu_show" => 0,
                            "title" => "字段编辑",
                        ],
                        [
                            "url" => "cms/field/edit",
                            "method" => "POST",
                            "slug" => "admin.cms.field-edit-save",
                            "listorder" => 6,
                            "menu_show" => 0,
                            "title" => "字段编辑保存",
                        ],
                        [
                            "url" => "cms/field/delete",
                            "method" => "POST",
                            "slug" => "admin.cms.field-delete",
                            "listorder" => 7,
                            "menu_show" => 0,
                            "title" => "字段删除",
                        ],
                        [
                            "url" => "cms/field/sort",
                            "method" => "POST",
                            "slug" => "admin.cms.field-sort",
                            "listorder" => 8,
                            "menu_show" => 0,
                            "title" => "字段排序",
                        ],
                        [
                            "url" => "cms/field/state",
                            "method" => "POST",
                            "slug" => "admin.cms.field-state",
                            "listorder" => 9,
                            "menu_show" => 0,
                            "title" => "字段状态",
                        ],
                    ],
                ],
                
                [
                    "url" => "cms/model/index",
                    "method" => "OPTIONS",
                    "slug" => "admin.cms.model-index",
                    "menu_show" => 1,
                    "title" => "模型管理",
                    "icon" => "icon-apartment",
                    "listorder" => 70,
                    "children" => [
                        [
                            "url" => "cms/model/index",
                            "method" => "GET",
                            "slug" => "admin.cms.model-index",
                            "listorder" => 1,
                            "menu_show" => 0,
                            "title" => "模型管理",
                        ],
                        [
                            "url" => "cms/model/index",
                            "method" => "POST",
                            "slug" => "admin.cms.model-index-data",
                            "listorder" => 2,
                            "menu_show" => 0,
                            "title" => "模型管理数据",
                        ],
                        [
                            "url" => "cms/model/add",
                            "method" => "GET",
                            "slug" => "admin.cms.model-add",
                            "listorder" => 3,
                            "menu_show" => 0,
                            "title" => "添加模型",
                        ],
                        [
                            "url" => "cms/model/add",
                            "method" => "POST",
                            "slug" => "admin.cms.model-add-save",
                            "listorder" => 4,
                            "menu_show" => 0,
                            "title" => "添加模型保存",
                        ],
                        [
                            "url" => "cms/model/edit",
                            "method" => "GET",
                            "slug" => "admin.cms.model-edit",
                            "listorder" => 5,
                            "menu_show" => 0,
                            "title" => "修改模型",
                        ],
                        [
                            "url" => "cms/model/edit",
                            "method" => "POST",
                            "slug" => "admin.cms.model-edit-save",
                            "listorder" => 6,
                            "menu_show" => 0,
                            "title" => "修改模型保存",
                        ],
                        [
                            "url" => "cms/model/delete",
                            "method" => "POST",
                            "slug" => "admin.cms.model-delete",
                            "listorder" => 7,
                            "menu_show" => 0,
                            "title" => "删除模型",
                        ],
                        [
                            "url" => "cms/model/sort",
                            "method" => "POST",
                            "slug" => "admin.cms.model-sort",
                            "listorder" => 8,
                            "menu_show" => 0,
                            "title" => "模型排序",
                        ],
                        [
                            "url" => "cms/model/state",
                            "method" => "POST",
                            "slug" => "admin.cms.model-state",
                            "listorder" => 9,
                            "menu_show" => 0,
                            "title" => "模型状态",
                        ],
                    ],
                ],
                
            ],
        ],
        
        
        [
            "url" => "cms/setting/index",
            "method" => "GET",
            "slug" => "admin.cms.setting-index",
            "menu_show" => 1,
            "title" => "网站设置",
            "icon" => "icon-setup",
            "listorder" => 30,
            "children" => [
                [
                    "url" => "cms/setting/theme",
                    "method" => "GET",
                    "slug" => "admin.cms.setting-theme",
                    "icon" => "icon-setup",
                    "menu_show" => 1,
                    "listorder" => 5,
                    "title" => "主题设置",
                ],
                [
                    "url" => "cms/setting/theme",
                    "method" => "POST",
                    "slug" => "admin.cms.setting-theme-save",
                    "menu_show" => 0,
                    "listorder" => 6,
                    "title" => "主题设置保存",
                ],
                
                [
                    "url" => "cms/setting/index",
                    "method" => "GET",
                    "slug" => "admin.cms.setting-index",
                    "icon" => "icon-setup",
                    "menu_show" => 1,
                    "listorder" => 15,
                    "title" => "常规设置",
                ],
                [
                    "url" => "cms/setting/index",
                    "method" => "POST",
                    "slug" => "admin.cms.setting-index-save",
                    "menu_show" => 0,
                    "listorder" => 16,
                    "title" => "常规设置保存",
                ],
            ],
        ],
        
    ],
];
